services:
  stremio:
    build: .
    image: stremio-docker:local
    restart: unless-stopped
    environment:
      NO_CORS: 1
      AUTO_SERVER_URL: 1
      #IPADDRESS: 192.168.1.10 # Setup your ip address here
    ports:
      - "8080:8080"
      - "11470:11470"
      - "12470:12470"
    volumes:
      - "./stremio-data:/root/.stremio-server"
